export const mvpEpochAbi = [
  { type: 'function', name: 'epochStart', inputs: [], outputs: [{ type: 'uint64' }], stateMutability: 'view' },
  { type: 'function', name: 'epochEnd', inputs: [], outputs: [{ type: 'uint64' }], stateMutability: 'view' },
  { type: 'function', name: 'finalized', inputs: [], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'isActive', inputs: [], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'playerCount', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'players', inputs: [{ type: 'uint256' }], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'registered', inputs: [{ type: 'address' }], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'mandateHashOf', inputs: [{ type: 'address' }], outputs: [{ type: 'bytes32' }], stateMutability: 'view' },
  { type: 'function', name: 'finalScore', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'currentValue', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'register', inputs: [{ type: 'bytes32' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'updateMandate', inputs: [{ type: 'bytes32' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'finalize', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'event', name: 'PlayerRegistered', inputs: [{ type: 'address', indexed: true }, { type: 'bytes32', indexed: false }] },
  { type: 'event', name: 'MandateUpdated', inputs: [{ type: 'address', indexed: true }, { type: 'bytes32', indexed: false }] },
  { type: 'event', name: 'EpochFinalized', inputs: [{ type: 'uint64' }, { type: 'uint256' }] },
  { type: 'event', name: 'PlayerScored', inputs: [{ type: 'address', indexed: true }, { type: 'uint256' }] },
] as const;
